name: csv
reportingTeam: cad-cdt
description: CSV library forked from encoding/csv without CRLF handling
slack: clerk
library: true
circleAPIKey: f28170e343fd8526a5d3e6cd427ebc93bbeb2803
lintroller: silver
tracing: honeycomb
metrics: datadog
releaseType: ""
deployTo:
  environments: []
arguments:
  circleAPIKey: f28170e343fd8526a5d3e6cd427ebc93bbeb2803
  commands: []
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: CSV library forked from encoding/csv without CRLF handling
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: silver
  metrics: datadog
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: false
  releaseOptions:
    allowMajorVersions: false
    enablePrereleases: false
    prereleasesBranch: ""
  reportingTeam: cad-cdt
  resources: {}
  service: false
  slack: clerk
  terraform:
    datadog:
      grpc:
        evaluationWindow: ""
        latency:
          percentiles:
            highTraffic: 0
            lowTraffic: 0
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        lowTrafficCountThreshold: 0
        qos:
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        tags: []
      http:
        evaluationWindow: ""
        percentiles:
          highTraffic: 0
          lowTraffic: 0
        thresholds:
          highTraffic: 0
          lowCount: 0
          lowTraffic: 0
      pods:
        thresholds:
          availableLowCount: 0
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
